// <auto-generated />
using GeoChat.Geolocation.Api.DbAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoChat.Geolocation.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230517165450_ServersAndTheirLocations")]
    partial class ServersAndTheirLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoChat.Geolocation.Api.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GeoHashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            GeoHashCode = "u2ph8",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            GeoHashCode = "u2ph9",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            GeoHashCode = "u2phd",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            GeoHashCode = "u2phe",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            GeoHashCode = "u2phs",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            GeoHashCode = "u2pht",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            GeoHashCode = "u2ph2",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            GeoHashCode = "u2ph3",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            GeoHashCode = "u2ph6",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            GeoHashCode = "u2ph7",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            GeoHashCode = "u2phk",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            GeoHashCode = "u2phm",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            GeoHashCode = "u2ph0",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            GeoHashCode = "u2ph1",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            GeoHashCode = "u2ph4",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            GeoHashCode = "u2ph5",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 17L,
                            GeoHashCode = "u2phh",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 18L,
                            GeoHashCode = "u2phj",
                            ServerId = 1L
                        },
                        new
                        {
                            Id = 19L,
                            GeoHashCode = "sxfsb",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            GeoHashCode = "sxfsc",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            GeoHashCode = "sxfsf",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            GeoHashCode = "sxfsg",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            GeoHashCode = "sxfsu",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            GeoHashCode = "sxfs8",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            GeoHashCode = "sxfs9",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            GeoHashCode = "sxfsd",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 27L,
                            GeoHashCode = "sxfse",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            GeoHashCode = "sxfss",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 29L,
                            GeoHashCode = "sxfs2",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 30L,
                            GeoHashCode = "sxfs3",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 31L,
                            GeoHashCode = "sxfs6",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 32L,
                            GeoHashCode = "sxfs7",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 33L,
                            GeoHashCode = "sxfsk",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 34L,
                            GeoHashCode = "sxfxz",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 35L,
                            GeoHashCode = "sxfxx",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 36L,
                            GeoHashCode = "sxfmp",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 37L,
                            GeoHashCode = "sxft3",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 38L,
                            GeoHashCode = "sxft6",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 39L,
                            GeoHashCode = "sxft0",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 40L,
                            GeoHashCode = "sxft1",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 41L,
                            GeoHashCode = "sxft4",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 42L,
                            GeoHashCode = "sxft5",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 43L,
                            GeoHashCode = "sxfth",
                            ServerId = 2L
                        },
                        new
                        {
                            Id = 44L,
                            GeoHashCode = "u82f0",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 45L,
                            GeoHashCode = "u82f1",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 46L,
                            GeoHashCode = "u82f4",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 47L,
                            GeoHashCode = "u82f5",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 48L,
                            GeoHashCode = "u82fh",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 49L,
                            GeoHashCode = "u82fk",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 50L,
                            GeoHashCode = "u82cb",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 51L,
                            GeoHashCode = "u82cc",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 52L,
                            GeoHashCode = "u82cf",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 53L,
                            GeoHashCode = "u829u",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 54L,
                            GeoHashCode = "u829v",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 55L,
                            GeoHashCode = "u829y",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 56L,
                            GeoHashCode = "u829z",
                            ServerId = 3L
                        },
                        new
                        {
                            Id = 57L,
                            GeoHashCode = "u82dp",
                            ServerId = 3L
                        });
                });

            modelBuilder.Entity("Server", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Name = "Default",
                            Url = ""
                        },
                        new
                        {
                            Id = 1L,
                            Name = "Timis",
                            Url = ""
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Bucuresti",
                            Url = ""
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Cluj-Napoca",
                            Url = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
